# Generated by Django 2.2.8 on 2020-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_man', '0002__init_isp_and_ap_20200121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['-updated_at', '-bk_host_id'], 'verbose_name': '主机信息', 'verbose_name_plural': '主机信息'},
        ),
        migrations.AddField(
            model_name='host',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='是否手动安装'),
        ),
    ]
