# Generated by Django 2.2.8 on 2020-05-18 04:09

from django.db import migrations, models
import django_mysql.models


def migrate_servers(apps, schema_editor):
    # 初始化默认接入点
    AccessPoint = apps.get_model("node_man", "AccessPoint")
    for ap in AccessPoint.objects.all():
        ap.btfileserver = ap.taskserver
        ap.dataserver = ap.taskserver
        ap.save()


class Migration(migrations.Migration):
    dependencies = [
        ("node_man", "0004_auto_20200509_1438"),
    ]

    operations = [
        migrations.RenameField(model_name="accesspoint", old_name="servers", new_name="taskserver",),
        migrations.AlterField(
            model_name="accesspoint",
            name="taskserver",
            field=django_mysql.models.JSONField(default=dict, verbose_name="GSE 任务服务器列表"),
        ),
        migrations.AddField(
            model_name="accesspoint",
            name="btfileserver",
            field=django_mysql.models.JSONField(default=dict, verbose_name="GSE BT文件服务器列表"),
        ),
        migrations.AddField(
            model_name="accesspoint",
            name="dataserver",
            field=django_mysql.models.JSONField(default=dict, verbose_name="GSE 数据服务器列表"),
        ),
        migrations.AddField(
            model_name="accesspoint",
            name="nginx_path",
            field=models.TextField(blank=True, null=True, verbose_name="Nginx路径"),
        ),
        migrations.AddField(
            model_name="pluginconfigtemplate",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="是否主配置"),
        ),
        migrations.RunPython(migrate_servers),
    ]
