# Generated by Django 2.2.8 on 2020-06-02 03:04

import apps.node_man.models
from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0005_auto_20200518_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="extra_data",
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name="额外数据"),
        ),
        migrations.AlterField(
            model_name="pipelinetree",
            name="tree",
            field=apps.node_man.models.LazyJSONField(default=dict, verbose_name="Pipeline拓扑树"),
        ),
    ]
