# Generated by Django 2.2.8 on 2020-06-05 11:22
from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0007_auto_20200604_2107"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="creator",
            field=django_mysql.models.JSONField(default=("admin",), verbose_name="接入点创建者"),
        ),
    ]
