# Generated by Django 2.2.8 on 2020-06-19 08:23

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0008_accesspoint_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceWatchEvent",
            fields=[
                ("bk_cursor", models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="游标")),
                (
                    "bk_event_type",
                    models.CharField(
                        choices=[("update", "update"), ("create", "create"), ("delete", "delete")],
                        max_length=32,
                        verbose_name="事件类型",
                    ),
                ),
                ("bk_resource", models.CharField(max_length=32, verbose_name="资源")),
                ("bk_detail", django_mysql.models.JSONField(default=dict, verbose_name="事件详情")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={"verbose_name": "资源监听事件", "verbose_name_plural": "资源监听事件",},
        ),
    ]
