# Generated by Django 2.2.8 on 2020-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0009_resourcewatchevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="os_type",
            field=models.CharField(
                choices=[("LINUX", "LINUX"), ("WINDOWS", "WINDOWS"), ("AIX", "AIX")],
                db_index=True,
                default="LINUX",
                max_length=45,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("INSTALL_PROXY", "INSTALL_PROXY"),
                    ("INSTALL_AGENT", "INSTALL_AGENT"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("REINSTALL_PROXY", "REINSTALL_PROXY"),
                    ("REINSTALL_AGENT", "REINSTALL_AGENT"),
                    ("REPLACE_PROXY", "REPLACE_PROXY"),
                    ("UNINSTALL_AGENT", "UNINSTALL_AGENT"),
                    ("REMOVE_AGENT", "REMOVE_AGENT"),
                    ("UNINSTALL_PROXY", "UNINSTALL_PROXY"),
                    ("UPGRADE_PROXY", "UPGRADE_PROXY"),
                    ("UPGRADE_AGENT", "UPGRADE_AGENT"),
                    ("IMPORT_PROXY", "IMPORT_PROXY"),
                    ("IMPORT_AGENT", "IMPORT_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("RELOAD_AGENT", "RELOAD_AGENT"),
                    ("RELOAD_PROXY", "RELOAD_PROXY"),
                    ("MAIN_START_PLUGIN", "MAIN_START_PLUGIN"),
                    ("MAIN_STOP_PLUGIN", "MAIN_STOP_PLUGIN"),
                    ("MAIN_RESTART_PLUGIN", "MAIN_RESTART_PLUGIN"),
                    ("MAIN_RELOAD_PLUGIN", "MAIN_RELOAD_PLUGIN"),
                    ("MAIN_DELEGATE_PLUGIN", "MAIN_DELEGATE_PLUGIN"),
                    ("MAIN_UNDELEGATE_PLUGIN", "MAIN_UNDELEGATE_PLUGIN"),
                    ("MAIN_INSTALL_PLUGIN", "MAIN_INSTALL_PLUGIN"),
                    ("UPDATE_AUTHINFO", "UPDATE_AUTHINFO"),
                    ("PACKING_PLUGIN", "PACKING_PLUGIN"),
                ],
                default="INSTALL_PROXY",
                max_length=45,
                verbose_name="作业类型",
            ),
        ),
    ]
