# Generated by Django 2.2.8 on 2020-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0010_auto_20200628_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstatus", name="retry_times", field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
    ]
