# Generated by Django 2.2.8 on 2020-08-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0013_auto_20200817_1220"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pluginconfigtemplate",
            unique_together={("plugin_name", "plugin_version", "name", "version", "is_main")},
        ),
    ]
