# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataapirecord',
            name='response_errors',
            field=models.TextField(default=None, null=True),
        ),
    ]
